/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Groovy project to get you started.
 * For more details take a look at the Groovy Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3-rc-3/userguide/tutorial_groovy_projects.html
 */

plugins {
    // Apply the groovy plugin to add support for Groovy
    groovy
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

val astTransformationClasspath by configurations.creating
val testAstTransformationClasspath by configurations.creating

configurations {
    implementation.get().extendsFrom(astTransformationClasspath)
    testImplementation.get().extendsFrom(testAstTransformationClasspath)
}

dependencies {
    // Use the latest Groovy version for building this library
    astTransformationClasspath("org.codehaus.groovy:groovy:2.5.6")

    // Use the awesome Spock testing and specification framework
    testAstTransformationClasspath("org.spockframework:spock-core:1.2-groovy-2.5")
    testAstTransformationClasspath(project(":ast-transformation"))
}

tasks.withType<GroovyCompile> {
    groovyOptions.configurationScript = file("compiler-plugin/src/main/groovy/config.groovy")
//    astTransformClasspath.from(astTransformationClasspath)
}

tasks.named<GroovyCompile>("compileTestGroovy") {
//    astTransformClasspath.from(testAstTransformationClasspath)
}
