/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package groovy.faster.compile

class Library {
    boolean someLibraryMethod() {
        println "Yeah!"
        true
    }

    private doStuff() {
        println "I am private"
        [1, 2].each {
            println it
        }
    }
}
